name: contract_generation
channels:
  - conda-forge
  - defaults

dependencies:
  # ===== 基础系统依赖 =====
  - ca-certificates
  - openssl
  - setuptools
  - sqlite
  - wheel
  - zlib

  # ===== Python环境 =====
  - python=3.9.21
  - pip

  # ===== pip包依赖 =====
  - pip:
      - --index-url https://mirrors.aliyun.com/pypi/simple/
      
      # 按字母顺序排列的完整依赖列表
      - aiohttp==3.8.6
      - aiosignal==1.3.2
      - anyio==3.7.1
      - async-timeout==4.0.3
      - attrs==25.3.0
      - babel==2.17.0
      - bcrypt==4.3.0
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - colorama==0.4.6
      - cryptography==45.0.4
      - dashscope==1.23.6
      - docxcompose==1.4.0
      - docxtpl==0.16.7
      - ecdsa==0.19.1
      - exceptiongroup==1.3.0
      - faiss-cpu==1.10.0
      - fastapi==0.104.1
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.25.1
      - huggingface-hub==0.19.4
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.1
      - lxml==6.0.0
      - markupSafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.6.3
      - networkx==3.2.1
      - nltk==3.9.1
      - numpy==1.26.3
      - packaging==25.0
      - pandas==2.1.4
      - passlib==1.7.4
      - pillow==11.3.0
      - ply==3.11
      - propcache==0.3.2
      - pyasn1==0.6.1
      - pycparser==2.22
      - pydantic==1.10.13
      - pyqt5==5.15.11
      - pyqt5_sip==12.17.0
      - pyqt6==6.6.1
      - pyqt6-qt6==6.6.1
      - pyqt6-sip==13.6.0
      - python-dateutil==2.9.0.post0
      - python-docx==1.1.0
      - python-dotenv==1.0.0
      - python-jose==3.3.0
      - python-multipart==0.0.6
      - pytz==2025.2
      - pyyaml==6.0.1
      - regex==2024.11.6
      - requests==2.32.3
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.13.1
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.0
      - sip==6.10.0
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.27.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.14.1
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.1.2
      - torchvision==0.16.2
      - tqdm==4.66.1
      - transformers==4.36.2
      - typing_extensions==4.14.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.23.2
      - websocket-client==1.8.0
      - yarl==1.20.1
      
      # 平台特定依赖
      - python-magic-bin==0.4.14; platform_system == "Windows"
      - python-magic==0.4.27; platform_system != "Windows"