name: contract_generator
channels:
  - conda-forge
  - defaults

dependencies:
  # ===== 系统级依赖 =====
  - ca-certificates
  - openssl
  - setuptools
  - sqlite
  - wheel
  - zlib

  # ===== Python 环境 =====
  - python=3.9.21
  - pip

  # ===== PIP 依赖 (分类管理) =====
  - pip:
      # 镜像源配置
      - --index-url https://mirrors.aliyun.com/pypi/simple/
      
      # ===== 核心框架 =====
      - fastapi==0.104.1
      - starlette==0.27.0
      - uvicorn==0.23.2
      - anyio==3.7.1
      - python-multipart==0.0.6
      
      # ===== 网络通信 =====
      - aiohttp==3.8.6
      - httpx==0.25.1
      - httpcore==1.0.9
      - requests==2.32.3
      - websocket-client==1.8.0
      - async-timeout==4.0.3
      - aiosignal==1.3.2
      - frozenlist==1.7.0
      - yarl==1.20.1
      - multidict==6.6.3
      - h11==0.16.0
      
      # ===== AI/ML 相关 =====
      - torch==2.1.2
      - torchvision==0.16.2
      - transformers==4.36.2
      - tokenizers==0.15.2  # 解决冲突的关键更新
      - huggingface-hub==0.19.4
      - sentence-transformers==2.2.2
      - faiss-cpu==1.10.0
      - scikit-learn==1.3.2
      - sentencepiece==0.2.0
      - safetensors==0.5.3
      
      # ===== 数据处理 =====
      - numpy==1.26.3
      - pandas==2.1.4
      - scipy==1.13.1
      - joblib==1.5.1
      - threadpoolctl==3.6.0
      
      # ===== NLP 工具 =====
      - nltk==3.9.1
      - regex==2024.11.6
      
      # ===== 文档处理 =====
      - docxcompose==1.4.0
      - docxtpl==0.16.7
      - python-docx==1.1.0
      - lxml==6.0.0
      
      # ===== 模板引擎 =====
      - jinja2==3.1.6
      - markupSafe==3.0.2
      
      # ===== 安全认证 =====
      - bcrypt==4.3.0
      - cryptography==45.0.4
      - python-jose==3.3.0
      - passlib==1.7.4
      - rsa==4.9.1
      - ecdsa==0.19.1
      
      # ===== 工具类库 =====
      - click==8.1.8
      - tqdm==4.66.1
      - filelock==3.18.0
      - fsspec==2025.5.1
      - python-dotenv==1.0.0
      - propcache==0.3.2
      - colorama==0.4.6
      
      # ===== 数据类型与序列化 =====
      - pydantic==1.10.13
      - pyyaml==6.0.1
      - toml==0.10.2
      - tomli==2.2.1
      
      # ===== 数学计算 =====
      - mpmath==1.3.0
      - sympy==1.14.0
      
      # ===== 日期时间 =====
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - tzdata==2025.2
      
      # ===== 编码/解码 =====
      - charset-normalizer==3.4.2
      - idna==3.10
      - cffi==1.17.1
      - pycparser==2.22
      
      # ===== 图形界面 (PyQt) =====
      - pyqt5==5.15.11
      - pyqt5_sip==12.17.0
      - pyqt6==6.6.1
      - pyqt6-qt6==6.6.1
      - pyqt6-sip==13.6.0
      - sip==6.10.0
      
      # ===== 其他必要依赖 =====
      - attrs==25.3.0
      - babel==2.17.0
      - certifi==2025.6.15
      - exceptiongroup==1.3.0
      - pillow==11.3.0
      - ply==3.11
      - pyasn1==0.6.1
      - six==1.17.0
      - sniffio==1.3.1
      - typing_extensions==4.14.0
      - urllib3==2.5.0
      - dashscope==1.23.6
      - networkx==3.2.1
      - packaging==25.0
      
      # ===== 平台特定依赖 =====
      - python-magic-bin==0.4.14; platform_system == "Windows"
      - python-magic==0.4.27; platform_system != "Windows"